export interface CIDEntry {
  code: string;
  name: string;
  chapter: string;
}

export const CID10_CHAPTERS = [
  { id: "all", label: "Todos" },
  { id: "A-B", label: "Infecciosas e Parasitárias" },
  { id: "C-D", label: "Neoplasias" },
  { id: "D5-D8", label: "Sangue e Órgãos Hematopoéticos" },
  { id: "E", label: "Endócrinas e Metabólicas" },
  { id: "F", label: "Transtornos Mentais" },
  { id: "G", label: "Sistema Nervoso" },
  { id: "H0-H5", label: "Olho e Anexos" },
  { id: "H6-H9", label: "Ouvido e Mastoide" },
  { id: "I", label: "Aparelho Circulatório" },
  { id: "J", label: "Aparelho Respiratório" },
  { id: "K", label: "Aparelho Digestivo" },
  { id: "L", label: "Pele e Tecido Subcutâneo" },
  { id: "M", label: "Musculoesquelético" },
  { id: "N", label: "Geniturinário" },
  { id: "O", label: "Gravidez e Parto" },
  { id: "R", label: "Sintomas e Sinais" },
  { id: "S-T", label: "Lesões e Traumatismos" },
  { id: "Z", label: "Fatores que Influenciam" },
];

export const CID10_LIST: CIDEntry[] = [
  // ── A-B: INFECCIOSAS E PARASITÁRIAS ─────────────────────────────────────────
  { chapter: "A-B", code: "A00", name: "Cólera" },
  { chapter: "A-B", code: "A01", name: "Febres tifóide e paratifóide" },
  { chapter: "A-B", code: "A02", name: "Outras infecções por Salmonella" },
  { chapter: "A-B", code: "A03", name: "Shiguelose" },
  { chapter: "A-B", code: "A04", name: "Outras infecções intestinais bacterianas" },
  { chapter: "A-B", code: "A05", name: "Outras intoxicações alimentares bacterianas" },
  { chapter: "A-B", code: "A06", name: "Amebíase" },
  { chapter: "A-B", code: "A07", name: "Outras doenças intestinais por protozoários" },
  { chapter: "A-B", code: "A08", name: "Infecções intestinais por vírus e outros agentes especificados" },
  { chapter: "A-B", code: "A09", name: "Gastroenterite e colite de origem infecciosa e não especificada" },
  { chapter: "A-B", code: "A15", name: "Tuberculose respiratória com confirmação bacteriológica" },
  { chapter: "A-B", code: "A16", name: "Tuberculose pulmonar sem confirmação bacteriológica" },
  { chapter: "A-B", code: "A17", name: "Tuberculose do sistema nervoso" },
  { chapter: "A-B", code: "A18", name: "Tuberculose de outros órgãos" },
  { chapter: "A-B", code: "A19", name: "Tuberculose miliar" },
  { chapter: "A-B", code: "A20", name: "Peste" },
  { chapter: "A-B", code: "A22", name: "Carbúnculo" },
  { chapter: "A-B", code: "A36", name: "Difteria" },
  { chapter: "A-B", code: "A37", name: "Coqueluche" },
  { chapter: "A-B", code: "A38", name: "Escarlatina" },
  { chapter: "A-B", code: "A39", name: "Infecção meningocócica" },
  { chapter: "A-B", code: "A40", name: "Septicemia estreptocócica" },
  { chapter: "A-B", code: "A41", name: "Outras septicemias" },
  { chapter: "A-B", code: "A46", name: "Erisipela" },
  { chapter: "A-B", code: "A48", name: "Outras doenças bacterianas não classificadas" },
  { chapter: "A-B", code: "A49", name: "Infecção bacteriana de localização não especificada" },
  { chapter: "A-B", code: "A50", name: "Sífilis congênita" },
  { chapter: "A-B", code: "A51", name: "Sífilis precoce" },
  { chapter: "A-B", code: "A52", name: "Sífilis tardia" },
  { chapter: "A-B", code: "A53", name: "Outras formas e as não especificadas de sífilis" },
  { chapter: "A-B", code: "A54", name: "Infecção gonocócica" },
  { chapter: "A-B", code: "A56", name: "Outras doenças sexualmente transmissíveis por Chlamydia" },
  { chapter: "A-B", code: "A57", name: "Cancro mole (Cancroide)" },
  { chapter: "A-B", code: "A59", name: "Tricomoníase" },
  { chapter: "A-B", code: "A60", name: "Infecção anogenital pelo vírus do herpes" },
  { chapter: "A-B", code: "A63", name: "Outras doenças de transmissão predominantemente sexual" },
  { chapter: "A-B", code: "A64", name: "Doença sexualmente transmissível não especificada" },
  { chapter: "A-B", code: "A87", name: "Meningite viral" },
  { chapter: "A-B", code: "A90", name: "Dengue clássica" },
  { chapter: "A-B", code: "A91", name: "Febre hemorrágica devida ao vírus do dengue" },
  { chapter: "A-B", code: "A92", name: "Outras febres virais transmitidas por mosquitos" },
  { chapter: "A-B", code: "A97", name: "Dengue – dengue hemorrágica" },
  { chapter: "A-B", code: "B00", name: "Infecções pelo vírus do herpes simples" },
  { chapter: "A-B", code: "B01", name: "Varicela (catapora)" },
  { chapter: "A-B", code: "B02", name: "Herpes zoster" },
  { chapter: "A-B", code: "B05", name: "Sarampo" },
  { chapter: "A-B", code: "B06", name: "Rubéola" },
  { chapter: "A-B", code: "B07", name: "Verrugas de origem viral" },
  { chapter: "A-B", code: "B08", name: "Outras infecções virais com lesões cutâneas" },
  { chapter: "A-B", code: "B15", name: "Hepatite aguda A" },
  { chapter: "A-B", code: "B16", name: "Hepatite aguda B" },
  { chapter: "A-B", code: "B17", name: "Outras hepatites virais agudas" },
  { chapter: "A-B", code: "B18", name: "Hepatite viral crônica" },
  { chapter: "A-B", code: "B19", name: "Hepatite viral não especificada" },
  { chapter: "A-B", code: "B20", name: "Doença pelo HIV resultando em doenças infecciosas e parasitárias" },
  { chapter: "A-B", code: "B21", name: "Doença pelo HIV resultando em neoplasias malignas" },
  { chapter: "A-B", code: "B22", name: "Doença pelo HIV resultando em outras doenças especificadas" },
  { chapter: "A-B", code: "B24", name: "Doença pelo HIV não especificada" },
  { chapter: "A-B", code: "B34", name: "Infecção viral de localização não especificada" },
  { chapter: "A-B", code: "B37", name: "Candidíase" },
  { chapter: "A-B", code: "B44", name: "Aspergilose" },
  { chapter: "A-B", code: "B45", name: "Criptococose" },
  { chapter: "A-B", code: "B50", name: "Malária por Plasmodium falciparum" },
  { chapter: "A-B", code: "B53", name: "Outras formas de malária confirmadas por exame parasitológico" },
  { chapter: "A-B", code: "B54", name: "Malária não especificada" },
  { chapter: "A-B", code: "B55", name: "Leishmaniose" },
  { chapter: "A-B", code: "B57", name: "Doença de Chagas" },
  { chapter: "A-B", code: "B65", name: "Esquistossomose" },
  { chapter: "A-B", code: "B77", name: "Ascaridíase" },
  { chapter: "A-B", code: "B79", name: "Tricuríase" },
  { chapter: "A-B", code: "B80", name: "Enterobíase (oxiuríase)" },
  { chapter: "A-B", code: "B85", name: "Pediculose e fitiríase" },
  { chapter: "A-B", code: "B86", name: "Escabiose (sarna)" },
  { chapter: "A-B", code: "B96.8", name: "Infecção por Klebsiella pneumoniae" },

  // ── C-D: NEOPLASIAS ──────────────────────────────────────────────────────────
  { chapter: "C-D", code: "C00", name: "Neoplasia maligna do lábio" },
  { chapter: "C-D", code: "C01", name: "Neoplasia maligna da base da língua" },
  { chapter: "C-D", code: "C02", name: "Neoplasia maligna de outras partes e de partes não especificadas da língua" },
  { chapter: "C-D", code: "C04", name: "Neoplasia maligna do assoalho da boca" },
  { chapter: "C-D", code: "C10", name: "Neoplasia maligna da orofaringe" },
  { chapter: "C-D", code: "C11", name: "Neoplasia maligna da nasofaringe" },
  { chapter: "C-D", code: "C14", name: "Neoplasia maligna de outras localizações da boca e da faringe" },
  { chapter: "C-D", code: "C15", name: "Neoplasia maligna do esôfago" },
  { chapter: "C-D", code: "C16", name: "Neoplasia maligna do estômago" },
  { chapter: "C-D", code: "C17", name: "Neoplasia maligna do intestino delgado" },
  { chapter: "C-D", code: "C18", name: "Neoplasia maligna do cólon" },
  { chapter: "C-D", code: "C19", name: "Neoplasia maligna da junção retossigmóide" },
  { chapter: "C-D", code: "C20", name: "Neoplasia maligna do reto" },
  { chapter: "C-D", code: "C21", name: "Neoplasia maligna do ânus e do canal anal" },
  { chapter: "C-D", code: "C22", name: "Neoplasia maligna do fígado e das vias biliares intra-hepáticas" },
  { chapter: "C-D", code: "C23", name: "Neoplasia maligna da vesícula biliar" },
  { chapter: "C-D", code: "C24", name: "Neoplasia maligna de outras partes das vias biliares" },
  { chapter: "C-D", code: "C25", name: "Neoplasia maligna do pâncreas" },
  { chapter: "C-D", code: "C30", name: "Neoplasia maligna da cavidade nasal e do ouvido médio" },
  { chapter: "C-D", code: "C32", name: "Neoplasia maligna da laringe" },
  { chapter: "C-D", code: "C33", name: "Neoplasia maligna da traqueia" },
  { chapter: "C-D", code: "C34", name: "Neoplasia maligna dos brônquios e dos pulmões" },
  { chapter: "C-D", code: "C40", name: "Neoplasia maligna dos ossos e cartilagens articulares dos membros" },
  { chapter: "C-D", code: "C43", name: "Melanoma maligno da pele" },
  { chapter: "C-D", code: "C44", name: "Outras neoplasias malignas da pele" },
  { chapter: "C-D", code: "C50", name: "Neoplasia maligna da mama" },
  { chapter: "C-D", code: "C51", name: "Neoplasia maligna da vulva" },
  { chapter: "C-D", code: "C52", name: "Neoplasia maligna da vagina" },
  { chapter: "C-D", code: "C53", name: "Neoplasia maligna do colo do útero" },
  { chapter: "C-D", code: "C54", name: "Neoplasia maligna do corpo do útero" },
  { chapter: "C-D", code: "C56", name: "Neoplasia maligna do ovário" },
  { chapter: "C-D", code: "C61", name: "Neoplasia maligna da próstata" },
  { chapter: "C-D", code: "C62", name: "Neoplasia maligna dos testículos" },
  { chapter: "C-D", code: "C64", name: "Neoplasia maligna do rim, exceto pelve renal" },
  { chapter: "C-D", code: "C65", name: "Neoplasia maligna da pelve renal" },
  { chapter: "C-D", code: "C67", name: "Neoplasia maligna da bexiga" },
  { chapter: "C-D", code: "C69", name: "Neoplasia maligna do olho e anexos" },
  { chapter: "C-D", code: "C71", name: "Neoplasia maligna do encéfalo" },
  { chapter: "C-D", code: "C72", name: "Neoplasia maligna da medula espinhal e de outras partes do SNC" },
  { chapter: "C-D", code: "C73", name: "Neoplasia maligna da glândula tireoide" },
  { chapter: "C-D", code: "C75", name: "Neoplasia maligna de outras glândulas endócrinas" },
  { chapter: "C-D", code: "C76", name: "Neoplasia maligna de outras localizações e de localizações mal definidas" },
  { chapter: "C-D", code: "C79", name: "Neoplasia maligna secundária de outros sítios" },
  { chapter: "C-D", code: "C80", name: "Neoplasia maligna sem especificação de localização" },
  { chapter: "C-D", code: "C81", name: "Doença de Hodgkin" },
  { chapter: "C-D", code: "C82", name: "Linfoma não Hodgkin folicular" },
  { chapter: "C-D", code: "C83", name: "Linfoma não Hodgkin difuso" },
  { chapter: "C-D", code: "C85", name: "Outros tipos e tipos não especificados de linfoma não Hodgkin" },
  { chapter: "C-D", code: "C90", name: "Mieloma múltiplo e neoplasias malignas de plasmócitos" },
  { chapter: "C-D", code: "C91", name: "Leucemia linfóide" },
  { chapter: "C-D", code: "C92", name: "Leucemia mieloide" },
  { chapter: "C-D", code: "C95", name: "Leucemia de tipo celular não especificado" },
  { chapter: "C-D", code: "D00", name: "Carcinoma in situ da cavidade oral, esôfago e estômago" },
  { chapter: "C-D", code: "D05", name: "Carcinoma in situ da mama" },
  { chapter: "C-D", code: "D06", name: "Carcinoma in situ do colo do útero" },
  { chapter: "C-D", code: "D21", name: "Outros neoplasmas benignos do tecido conjuntivo e tecidos moles" },
  { chapter: "C-D", code: "D25", name: "Leiomioma do útero" },
  { chapter: "C-D", code: "D27", name: "Neoplasma benigno do ovário" },
  { chapter: "C-D", code: "D32", name: "Neoplasma benigno das meninges" },
  { chapter: "C-D", code: "D33", name: "Neoplasma benigno do encéfalo" },
  { chapter: "C-D", code: "D35", name: "Neoplasma benigno de outras glândulas endócrinas" },

  // ── D5-D8: SANGUE E ÓRGÃOS HEMATOPOÉTICOS ───────────────────────────────────
  { chapter: "D5-D8", code: "D50", name: "Anemias por deficiência de ferro" },
  { chapter: "D5-D8", code: "D51", name: "Anemia por deficiência de vitamina B12" },
  { chapter: "D5-D8", code: "D52", name: "Anemia por deficiência de folato" },
  { chapter: "D5-D8", code: "D53", name: "Outras anemias nutricionais" },
  { chapter: "D5-D8", code: "D55", name: "Anemia devida a transtornos enzimáticos" },
  { chapter: "D5-D8", code: "D56", name: "Talassemia" },
  { chapter: "D5-D8", code: "D57", name: "Transtornos falciformes (anemia falciforme)" },
  { chapter: "D5-D8", code: "D60", name: "Aplasia eritroide adquirida pura" },
  { chapter: "D5-D8", code: "D61", name: "Outras anemias aplásticas" },
  { chapter: "D5-D8", code: "D64", name: "Outras anemias" },
  { chapter: "D5-D8", code: "D65", name: "Coagulação intravascular disseminada (CIVD)" },
  { chapter: "D5-D8", code: "D68", name: "Outros defeitos da coagulação" },
  { chapter: "D5-D8", code: "D69", name: "Púrpura e outras afecções hemorrágicas" },
  { chapter: "D5-D8", code: "D70", name: "Agranulocitose" },
  { chapter: "D5-D8", code: "D72", name: "Outros transtornos dos leucócitos" },
  { chapter: "D5-D8", code: "D80", name: "Imunodeficiências com predominância de defeitos de anticorpos" },
  { chapter: "D5-D8", code: "D84", name: "Outras imunodeficiências" },

  // ── E: ENDÓCRINAS E METABÓLICAS ──────────────────────────────────────────────
  { chapter: "E", code: "E00", name: "Síndrome da deficiência congênita de iodo" },
  { chapter: "E", code: "E01", name: "Transtornos da tireoide associados à deficiência de iodo e afecções relacionadas" },
  { chapter: "E", code: "E02", name: "Hipotireoidismo subclínico por deficiência de iodo" },
  { chapter: "E", code: "E03", name: "Outro hipotireoidismo" },
  { chapter: "E", code: "E04", name: "Outros bócios não tóxicos" },
  { chapter: "E", code: "E05", name: "Tireotoxicose (hipertireoidismo)" },
  { chapter: "E", code: "E06", name: "Tireoidite" },
  { chapter: "E", code: "E07", name: "Outros transtornos da tireoide" },
  { chapter: "E", code: "E10", name: "Diabetes mellitus insulinodependente (tipo 1)" },
  { chapter: "E", code: "E11", name: "Diabetes mellitus não insulinodependente (tipo 2)" },
  { chapter: "E", code: "E13", name: "Outros tipos especificados de diabetes mellitus" },
  { chapter: "E", code: "E14", name: "Diabetes mellitus não especificado" },
  { chapter: "E", code: "E16", name: "Outros transtornos da secreção interna do pâncreas" },
  { chapter: "E", code: "E20", name: "Hipoparatireoidismo" },
  { chapter: "E", code: "E21", name: "Hiperparatireoidismo e outros transtornos da glândula paratireoide" },
  { chapter: "E", code: "E22", name: "Hiperfunção da hipófise" },
  { chapter: "E", code: "E23", name: "Hipofunção e outros transtornos da hipófise" },
  { chapter: "E", code: "E24", name: "Síndrome de Cushing" },
  { chapter: "E", code: "E25", name: "Transtornos adrenogenitais" },
  { chapter: "E", code: "E26", name: "Hiperaldosteronismo" },
  { chapter: "E", code: "E27", name: "Outros transtornos da suprarrenal" },
  { chapter: "E", code: "E28", name: "Disfunção ovariana" },
  { chapter: "E", code: "E29", name: "Disfunção testicular" },
  { chapter: "E", code: "E34", name: "Outros transtornos endócrinos" },
  { chapter: "E", code: "E40", name: "Kwashiorkor" },
  { chapter: "E", code: "E43", name: "Desnutrição protéico-calórica grave não especificada" },
  { chapter: "E", code: "E46", name: "Desnutrição não especificada" },
  { chapter: "E", code: "E50", name: "Deficiência de vitamina A" },
  { chapter: "E", code: "E55", name: "Deficiência de vitamina D (raquitismo, osteomalácia)" },
  { chapter: "E", code: "E58", name: "Deficiência dietética de cálcio" },
  { chapter: "E", code: "E61", name: "Deficiência de outros elementos nutricionais" },
  { chapter: "E", code: "E63", name: "Outras deficiências nutricionais" },
  { chapter: "E", code: "E66", name: "Obesidade" },
  { chapter: "E", code: "E70", name: "Transtornos do metabolismo de aminoácidos aromáticos" },
  { chapter: "E", code: "E78", name: "Transtornos do metabolismo das lipoproteínas e outras lipidemias" },
  { chapter: "E", code: "E79", name: "Transtornos do metabolismo das purinas e das pirimidinas (hiperuricemia)" },
  { chapter: "E", code: "E83", name: "Transtornos do metabolismo de minerais" },
  { chapter: "E", code: "E84", name: "Fibrose cística" },
  { chapter: "E", code: "E85", name: "Amiloidose" },
  { chapter: "E", code: "E86", name: "Depleção de volume (desidratação)" },
  { chapter: "E", code: "E87", name: "Outros transtornos do equilíbrio eletrolítico e hídrico" },
  { chapter: "E", code: "E88", name: "Outros transtornos metabólicos" },

  // ── F: TRANSTORNOS MENTAIS ───────────────────────────────────────────────────
  { chapter: "F", code: "F00", name: "Demência na doença de Alzheimer" },
  { chapter: "F", code: "F01", name: "Demência vascular" },
  { chapter: "F", code: "F02", name: "Demência em outras doenças classificadas em outra parte" },
  { chapter: "F", code: "F03", name: "Demência não especificada" },
  { chapter: "F", code: "F04", name: "Síndrome amnéstica orgânica não induzida pelo álcool" },
  { chapter: "F", code: "F05", name: "Delirium não superposto a demência" },
  { chapter: "F", code: "F06", name: "Outros transtornos mentais devidos a lesão e disfunção cerebral" },
  { chapter: "F", code: "F10", name: "Transtornos mentais e comportamentais devidos ao uso de álcool" },
  { chapter: "F", code: "F11", name: "Transtornos mentais devidos ao uso de opioides" },
  { chapter: "F", code: "F12", name: "Transtornos mentais devidos ao uso de canabinoides" },
  { chapter: "F", code: "F14", name: "Transtornos mentais devidos ao uso de cocaína" },
  { chapter: "F", code: "F17", name: "Transtornos mentais devidos ao uso de tabaco" },
  { chapter: "F", code: "F19", name: "Transtornos mentais devidos ao uso de múltiplas drogas" },
  { chapter: "F", code: "F20", name: "Esquizofrenia" },
  { chapter: "F", code: "F21", name: "Transtorno esquizotípico" },
  { chapter: "F", code: "F22", name: "Transtornos delirantes persistentes" },
  { chapter: "F", code: "F25", name: "Transtornos esquizoafetivos" },
  { chapter: "F", code: "F29", name: "Psicose não orgânica não especificada" },
  { chapter: "F", code: "F30", name: "Episódio maníaco" },
  { chapter: "F", code: "F31", name: "Transtorno afetivo bipolar" },
  { chapter: "F", code: "F32", name: "Episódio depressivo" },
  { chapter: "F", code: "F33", name: "Transtorno depressivo recorrente" },
  { chapter: "F", code: "F34", name: "Transtornos de humor persistentes (distimia, ciclotimia)" },
  { chapter: "F", code: "F39", name: "Transtorno do humor não especificado" },
  { chapter: "F", code: "F40", name: "Transtornos fóbico-ansiosos" },
  { chapter: "F", code: "F41", name: "Outros transtornos ansiosos (transtorno de pânico, TAG)" },
  { chapter: "F", code: "F42", name: "Transtorno obsessivo-compulsivo" },
  { chapter: "F", code: "F43", name: "Reações ao stress grave e transtornos de adaptação (TEPT)" },
  { chapter: "F", code: "F44", name: "Transtornos dissociativos (conversivos)" },
  { chapter: "F", code: "F45", name: "Transtornos somatoformes" },
  { chapter: "F", code: "F48", name: "Outros transtornos neuróticos" },
  { chapter: "F", code: "F50", name: "Transtornos alimentares (anorexia, bulimia)" },
  { chapter: "F", code: "F51", name: "Transtornos do sono não orgânicos (insônia)" },
  { chapter: "F", code: "F52", name: "Disfunção sexual não orgânica" },
  { chapter: "F", code: "F60", name: "Transtornos específicos de personalidade" },
  { chapter: "F", code: "F70", name: "Retardo mental leve" },
  { chapter: "F", code: "F84", name: "Transtornos globais do desenvolvimento (autismo)" },
  { chapter: "F", code: "F90", name: "Transtornos hipercinéticos (TDAH)" },

  // ── G: SISTEMA NERVOSO ───────────────────────────────────────────────────────
  { chapter: "G", code: "G00", name: "Meningite bacteriana" },
  { chapter: "G", code: "G03", name: "Meningite devida a outras causas e causas não especificadas" },
  { chapter: "G", code: "G04", name: "Encefalite, mielite e encefalomielite" },
  { chapter: "G", code: "G06", name: "Abscesso e granuloma intracraniano e intravertebral" },
  { chapter: "G", code: "G10", name: "Doença de Huntington" },
  { chapter: "G", code: "G11", name: "Ataxia hereditária" },
  { chapter: "G", code: "G12", name: "Atrofia muscular espinhal e síndromes correlatas" },
  { chapter: "G", code: "G20", name: "Doença de Parkinson" },
  { chapter: "G", code: "G21", name: "Parkinsonismo secundário" },
  { chapter: "G", code: "G30", name: "Doença de Alzheimer" },
  { chapter: "G", code: "G35", name: "Esclerose múltipla" },
  { chapter: "G", code: "G36", name: "Outras desmielinizações disseminadas agudas" },
  { chapter: "G", code: "G37", name: "Outras doenças desmielinizantes do SNC" },
  { chapter: "G", code: "G40", name: "Epilepsia" },
  { chapter: "G", code: "G41", name: "Estado de mal epiléptico" },
  { chapter: "G", code: "G43", name: "Enxaqueca (migrânea)" },
  { chapter: "G", code: "G44", name: "Outras síndromes de algias cefálicas" },
  { chapter: "G", code: "G45", name: "Ataques isquêmicos transitórios e síndromes correlatas" },
  { chapter: "G", code: "G47", name: "Transtornos do sono (insônia, apneia do sono)" },
  { chapter: "G", code: "G50", name: "Transtornos do nervo trigêmeo" },
  { chapter: "G", code: "G51", name: "Transtornos do nervo facial (paralisia de Bell)" },
  { chapter: "G", code: "G54", name: "Transtornos das raízes e plexos nervosos" },
  { chapter: "G", code: "G56", name: "Mononeuropatias dos membros superiores (síndrome do túnel do carpo)" },
  { chapter: "G", code: "G57", name: "Mononeuropatias dos membros inferiores" },
  { chapter: "G", code: "G60", name: "Neuropatia hereditária e idiopática" },
  { chapter: "G", code: "G61", name: "Polineuropatia inflamatória (Guillain-Barré)" },
  { chapter: "G", code: "G62", name: "Outras polineuropatias" },
  { chapter: "G", code: "G63", name: "Polineuropatia em doenças classificadas em outra parte (diabética)" },
  { chapter: "G", code: "G70", name: "Miastenia gravis e outros transtornos neuromusculares" },
  { chapter: "G", code: "G71", name: "Transtornos primários dos músculos (miopatia)" },
  { chapter: "G", code: "G80", name: "Paralisia cerebral" },
  { chapter: "G", code: "G81", name: "Hemiplegia" },
  { chapter: "G", code: "G82", name: "Paraplegia e tetraplegia" },
  { chapter: "G", code: "G89", name: "Dor não classificada em outra parte (dor crônica)" },
  { chapter: "G", code: "G91", name: "Hidrocefalia" },
  { chapter: "G", code: "G93", name: "Outros transtornos do encéfalo" },

  // ── H0-H5: OLHO E ANEXOS ─────────────────────────────────────────────────────
  { chapter: "H0-H5", code: "H00", name: "Hordéolo e calázio" },
  { chapter: "H0-H5", code: "H01", name: "Outras inflamações da pálpebra" },
  { chapter: "H0-H5", code: "H04", name: "Transtornos do aparelho lacrimal" },
  { chapter: "H0-H5", code: "H10", name: "Conjuntivite" },
  { chapter: "H0-H5", code: "H11", name: "Outros transtornos da conjuntiva" },
  { chapter: "H0-H5", code: "H15", name: "Transtornos da esclera" },
  { chapter: "H0-H5", code: "H16", name: "Ceratite (queratite)" },
  { chapter: "H0-H5", code: "H17", name: "Cicatrizes e opacidades da córnea" },
  { chapter: "H0-H5", code: "H20", name: "Iridociclite" },
  { chapter: "H0-H5", code: "H25", name: "Catarata senil" },
  { chapter: "H0-H5", code: "H26", name: "Outras cataratas" },
  { chapter: "H0-H5", code: "H33", name: "Descolamento e defeitos da retina" },
  { chapter: "H0-H5", code: "H35", name: "Outros transtornos da retina (retinopatia diabética)" },
  { chapter: "H0-H5", code: "H40", name: "Glaucoma" },
  { chapter: "H0-H5", code: "H43", name: "Transtornos do corpo vítreo" },
  { chapter: "H0-H5", code: "H50", name: "Outros estrabismos" },
  { chapter: "H0-H5", code: "H52", name: "Transtornos da refração e da acomodação (miopia, astigmatismo)" },
  { chapter: "H0-H5", code: "H53", name: "Distúrbios visuais" },
  { chapter: "H0-H5", code: "H54", name: "Cegueira e visão subnormal" },

  // ── H6-H9: OUVIDO E MASTOIDE ─────────────────────────────────────────────────
  { chapter: "H6-H9", code: "H60", name: "Otite externa" },
  { chapter: "H6-H9", code: "H61", name: "Outros transtornos do ouvido externo" },
  { chapter: "H6-H9", code: "H65", name: "Otite média não supurativa" },
  { chapter: "H6-H9", code: "H66", name: "Otite média supurativa e não especificada" },
  { chapter: "H6-H9", code: "H70", name: "Mastoidite e afecções relacionadas" },
  { chapter: "H6-H9", code: "H72", name: "Perfuração da membrana do tímpano" },
  { chapter: "H6-H9", code: "H81", name: "Transtornos da função vestibular (vertigem, labirintite)" },
  { chapter: "H6-H9", code: "H83", name: "Outros transtornos do ouvido interno" },
  { chapter: "H6-H9", code: "H90", name: "Perda de audição de condução e neurossensorial" },
  { chapter: "H6-H9", code: "H91", name: "Outras perdas de audição (presbiacusia)" },
  { chapter: "H6-H9", code: "H92", name: "Otalgia e derrame do ouvido (zumbido)" },

  // ── I: APARELHO CIRCULATÓRIO ─────────────────────────────────────────────────
  { chapter: "I", code: "I00", name: "Febre reumática sem menção de comprometimento do coração" },
  { chapter: "I", code: "I01", name: "Febre reumática com comprometimento do coração" },
  { chapter: "I", code: "I05", name: "Doenças reumáticas da valva mitral" },
  { chapter: "I", code: "I06", name: "Doenças reumáticas da valva aórtica" },
  { chapter: "I", code: "I08", name: "Doenças de múltiplas valvas cardíacas" },
  { chapter: "I", code: "I10", name: "Hipertensão arterial essencial (primária)" },
  { chapter: "I", code: "I11", name: "Cardiopatia hipertensiva" },
  { chapter: "I", code: "I12", name: "Nefropatia hipertensiva" },
  { chapter: "I", code: "I13", name: "Cardiopatia e nefropatia hipertensiva" },
  { chapter: "I", code: "I15", name: "Hipertensão secundária" },
  { chapter: "I", code: "I20", name: "Angina pectoris" },
  { chapter: "I", code: "I21", name: "Infarto agudo do miocárdio (IAM)" },
  { chapter: "I", code: "I22", name: "Infarto do miocárdio recorrente" },
  { chapter: "I", code: "I24", name: "Outras doenças isquêmicas agudas do coração (síndrome coronariana aguda)" },
  { chapter: "I", code: "I25", name: "Doença isquêmica crônica do coração" },
  { chapter: "I", code: "I26", name: "Embolia pulmonar (tromboembolismo pulmonar)" },
  { chapter: "I", code: "I27", name: "Outras doenças cardiopulmonares (hipertensão pulmonar)" },
  { chapter: "I", code: "I30", name: "Pericardite aguda" },
  { chapter: "I", code: "I33", name: "Endocardite aguda e subaguda" },
  { chapter: "I", code: "I34", name: "Transtornos não reumáticos da valva mitral" },
  { chapter: "I", code: "I35", name: "Transtornos não reumáticos da valva aórtica" },
  { chapter: "I", code: "I38", name: "Endocardite de valva não especificada" },
  { chapter: "I", code: "I40", name: "Miocardite aguda" },
  { chapter: "I", code: "I42", name: "Cardiomiopatias" },
  { chapter: "I", code: "I44", name: "Bloqueio atrioventricular e do ramo esquerdo" },
  { chapter: "I", code: "I47", name: "Taquicardia paroxística" },
  { chapter: "I", code: "I48", name: "Fibrilação e flutter atrial" },
  { chapter: "I", code: "I49", name: "Outras arritmias cardíacas" },
  { chapter: "I", code: "I50", name: "Insuficiência cardíaca (ICC)" },
  { chapter: "I", code: "I51", name: "Complicações e doenças cardíacas mal definidas" },
  { chapter: "I", code: "I60", name: "Hemorragia subaracnóide" },
  { chapter: "I", code: "I61", name: "Hemorragia intracerebral" },
  { chapter: "I", code: "I62", name: "Outras hemorragias intracranianas não traumáticas" },
  { chapter: "I", code: "I63", name: "Infarto cerebral (AVC isquêmico)" },
  { chapter: "I", code: "I64", name: "Acidente vascular cerebral não especificado (AVC)" },
  { chapter: "I", code: "I65", name: "Oclusão e estenose das artérias pré-cerebrais" },
  { chapter: "I", code: "I67", name: "Outras doenças cerebrovasculares (aneurisma cerebral)" },
  { chapter: "I", code: "I69", name: "Sequelas de doenças cerebrovasculares" },
  { chapter: "I", code: "I70", name: "Aterosclerose" },
  { chapter: "I", code: "I71", name: "Aneurisma e dissecção da aorta" },
  { chapter: "I", code: "I72", name: "Outros aneurismas" },
  { chapter: "I", code: "I73", name: "Outras doenças vasculares periféricas" },
  { chapter: "I", code: "I74", name: "Embolia e trombose arteriais" },
  { chapter: "I", code: "I80", name: "Flebite e tromboflebite" },
  { chapter: "I", code: "I82", name: "Outra embolia e trombose venosas (TVP)" },
  { chapter: "I", code: "I83", name: "Varizes dos membros inferiores" },
  { chapter: "I", code: "I84", name: "Hemorroidas" },
  { chapter: "I", code: "I87", name: "Outros transtornos das veias (insuficiência venosa crônica)" },

  // ── J: APARELHO RESPIRATÓRIO ─────────────────────────────────────────────────
  { chapter: "J", code: "J00", name: "Nasofaringite aguda (resfriado comum)" },
  { chapter: "J", code: "J01", name: "Sinusite aguda" },
  { chapter: "J", code: "J02", name: "Faringite aguda" },
  { chapter: "J", code: "J03", name: "Amigdalite aguda" },
  { chapter: "J", code: "J04", name: "Laringite e traqueíte agudas" },
  { chapter: "J", code: "J05", name: "Laringotraqueíte aguda obstrutiva e epiglotite" },
  { chapter: "J", code: "J06", name: "Infecções agudas das vias aéreas superiores de localizações múltiplas" },
  { chapter: "J", code: "J09", name: "Influenza por vírus influenza aviária" },
  { chapter: "J", code: "J10", name: "Influenza devida ao vírus influenza identificado" },
  { chapter: "J", code: "J11", name: "Influenza devida a vírus não identificado (gripe)" },
  { chapter: "J", code: "J12", name: "Pneumonia viral não classificada em outra parte" },
  { chapter: "J", code: "J13", name: "Pneumonia devida ao Streptococcus pneumoniae" },
  { chapter: "J", code: "J15", name: "Pneumonia bacteriana não classificada em outra parte" },
  { chapter: "J", code: "J18", name: "Pneumonia por microorganismo não especificado" },
  { chapter: "J", code: "J20", name: "Bronquite aguda" },
  { chapter: "J", code: "J21", name: "Bronquiolite aguda" },
  { chapter: "J", code: "J22", name: "Infecção aguda não especificada das vias aéreas inferiores" },
  { chapter: "J", code: "J30", name: "Rinite alérgica e vasomotora" },
  { chapter: "J", code: "J31", name: "Rinite crônica, nasofaringite e faringoamigdalite crônica" },
  { chapter: "J", code: "J32", name: "Sinusite crônica" },
  { chapter: "J", code: "J35", name: "Doenças crônicas das amígdalas e das adenoides" },
  { chapter: "J", code: "J38", name: "Doenças das pregas vocais e da laringe" },
  { chapter: "J", code: "J40", name: "Bronquite não especificada como aguda ou crônica" },
  { chapter: "J", code: "J41", name: "Bronquite crônica simples e mucopurulenta" },
  { chapter: "J", code: "J42", name: "Bronquite crônica não especificada" },
  { chapter: "J", code: "J43", name: "Enfisema" },
  { chapter: "J", code: "J44", name: "Outras doenças pulmonares obstrutivas crônicas (DPOC)" },
  { chapter: "J", code: "J45", name: "Asma" },
  { chapter: "J", code: "J46", name: "Estado de mal asmático" },
  { chapter: "J", code: "J47", name: "Bronquiectasia" },
  { chapter: "J", code: "J60", name: "Pneumoconiose dos mineiros de carvão" },
  { chapter: "J", code: "J68", name: "Afecções respiratórias devidas a inalação de agentes químicos" },
  { chapter: "J", code: "J69", name: "Pneumonite devida a sólidos e líquidos (pneumonia aspirativa)" },
  { chapter: "J", code: "J70", name: "Afecções respiratórias devidas a outros agentes externos" },
  { chapter: "J", code: "J80", name: "Síndrome do desconforto respiratório agudo (SDRA)" },
  { chapter: "J", code: "J81", name: "Edema pulmonar" },
  { chapter: "J", code: "J85", name: "Abscesso do pulmão e do mediastino" },
  { chapter: "J", code: "J86", name: "Piotórax (empiema)" },
  { chapter: "J", code: "J90", name: "Derrame pleural não classificado em outra parte" },
  { chapter: "J", code: "J93", name: "Pneumotórax" },
  { chapter: "J", code: "J96", name: "Insuficiência respiratória não classificada em outra parte" },
  { chapter: "J", code: "J98", name: "Outros transtornos respiratórios" },

  // ── K: APARELHO DIGESTIVO ────────────────────────────────────────────────────
  { chapter: "K", code: "K00", name: "Transtornos do desenvolvimento e da erupção dos dentes" },
  { chapter: "K", code: "K02", name: "Cárie dentária" },
  { chapter: "K", code: "K04", name: "Doenças da polpa e dos tecidos periapicais" },
  { chapter: "K", code: "K05", name: "Gengivite e doenças periodontais" },
  { chapter: "K", code: "K12", name: "Estomatite e lesões correlatas (aftas)" },
  { chapter: "K", code: "K20", name: "Esofagite" },
  { chapter: "K", code: "K21", name: "Doença do refluxo gastroesofágico (DRGE)" },
  { chapter: "K", code: "K22", name: "Outras doenças do esôfago" },
  { chapter: "K", code: "K25", name: "Úlcera gástrica" },
  { chapter: "K", code: "K26", name: "Úlcera duodenal" },
  { chapter: "K", code: "K27", name: "Úlcera péptica de localização não especificada" },
  { chapter: "K", code: "K28", name: "Úlcera gastrojejunal" },
  { chapter: "K", code: "K29", name: "Gastrite e duodenite" },
  { chapter: "K", code: "K30", name: "Dispepsia" },
  { chapter: "K", code: "K35", name: "Apendicite aguda" },
  { chapter: "K", code: "K37", name: "Apendicite sem especificação" },
  { chapter: "K", code: "K40", name: "Hérnia inguinal" },
  { chapter: "K", code: "K41", name: "Hérnia femoral" },
  { chapter: "K", code: "K42", name: "Hérnia umbilical" },
  { chapter: "K", code: "K43", name: "Hérnia ventral" },
  { chapter: "K", code: "K44", name: "Hérnia diafragmática" },
  { chapter: "K", code: "K46", name: "Hérnia abdominal não especificada" },
  { chapter: "K", code: "K50", name: "Doença de Crohn (enterite regional)" },
  { chapter: "K", code: "K51", name: "Colite ulcerativa" },
  { chapter: "K", code: "K52", name: "Outras gastroenterites e colites não infecciosas" },
  { chapter: "K", code: "K55", name: "Transtornos vasculares do intestino (isquemia mesentérica)" },
  { chapter: "K", code: "K56", name: "Íleo paralítico e obstrução intestinal" },
  { chapter: "K", code: "K57", name: "Doença diverticular do intestino (diverticulite)" },
  { chapter: "K", code: "K58", name: "Síndrome do intestino irritável" },
  { chapter: "K", code: "K59", name: "Outros transtornos funcionais do intestino (constipação, megacólon)" },
  { chapter: "K", code: "K60", name: "Fissura e fístula das regiões anal e retal" },
  { chapter: "K", code: "K61", name: "Abscesso da região anal e retal" },
  { chapter: "K", code: "K62", name: "Outras doenças do ânus e do reto (pólipo retal)" },
  { chapter: "K", code: "K63", name: "Outras doenças do intestino" },
  { chapter: "K", code: "K70", name: "Doença alcoólica do fígado" },
  { chapter: "K", code: "K71", name: "Doença tóxica do fígado" },
  { chapter: "K", code: "K72", name: "Insuficiência hepática" },
  { chapter: "K", code: "K73", name: "Hepatite crônica não classificada em outra parte" },
  { chapter: "K", code: "K74", name: "Fibrose e cirrose hepáticas" },
  { chapter: "K", code: "K75", name: "Outras doenças inflamatórias do fígado (hepatite autoimune)" },
  { chapter: "K", code: "K76", name: "Outras doenças do fígado (esteatose hepática não alcoólica – NASH)" },
  { chapter: "K", code: "K80", name: "Colelitíase (cálculo biliar)" },
  { chapter: "K", code: "K81", name: "Colecistite" },
  { chapter: "K", code: "K82", name: "Outras doenças da vesícula biliar" },
  { chapter: "K", code: "K83", name: "Outras doenças das vias biliares (colangite)" },
  { chapter: "K", code: "K85", name: "Pancreatite aguda" },
  { chapter: "K", code: "K86", name: "Outras doenças do pâncreas (pancreatite crônica)" },
  { chapter: "K", code: "K92", name: "Outras doenças do aparelho digestivo (hemorragia gastrointestinal)" },

  // ── L: PELE E TECIDO SUBCUTÂNEO ──────────────────────────────────────────────
  { chapter: "L", code: "L01", name: "Impetigo" },
  { chapter: "L", code: "L02", name: "Abscesso cutâneo, furúnculo e carbúnculo" },
  { chapter: "L", code: "L03", name: "Celulite" },
  { chapter: "L", code: "L04", name: "Linfadenite aguda" },
  { chapter: "L", code: "L08", name: "Outras infecções locais da pele e do tecido subcutâneo" },
  { chapter: "L", code: "L10", name: "Pênfigo" },
  { chapter: "L", code: "L12", name: "Penfigoide" },
  { chapter: "L", code: "L20", name: "Dermatite atópica (eczema)" },
  { chapter: "L", code: "L21", name: "Dermatite seborreica" },
  { chapter: "L", code: "L22", name: "Dermatite das fraldas" },
  { chapter: "L", code: "L23", name: "Dermatite alérgica de contato" },
  { chapter: "L", code: "L24", name: "Dermatite de contato por irritantes" },
  { chapter: "L", code: "L25", name: "Dermatite de contato não especificada" },
  { chapter: "L", code: "L27", name: "Dermatite devida a substâncias de uso interno" },
  { chapter: "L", code: "L29", name: "Prurido" },
  { chapter: "L", code: "L30", name: "Outras dermatites" },
  { chapter: "L", code: "L40", name: "Psoríase" },
  { chapter: "L", code: "L41", name: "Parapsoriase" },
  { chapter: "L", code: "L42", name: "Pitiríase rósea" },
  { chapter: "L", code: "L43", name: "Líquen plano" },
  { chapter: "L", code: "L50", name: "Urticária" },
  { chapter: "L", code: "L51", name: "Eritema multiforme" },
  { chapter: "L", code: "L52", name: "Eritema nodoso" },
  { chapter: "L", code: "L57", name: "Alterações da pele devidas à exposição crônica a radiação não ionizante" },
  { chapter: "L", code: "L60", name: "Transtornos das unhas" },
  { chapter: "L", code: "L63", name: "Alopecia areata" },
  { chapter: "L", code: "L64", name: "Alopecia androgenética" },
  { chapter: "L", code: "L70", name: "Acne" },
  { chapter: "L", code: "L71", name: "Rosácea" },
  { chapter: "L", code: "L72", name: "Cistos foliculares da pele e do tecido subcutâneo" },
  { chapter: "L", code: "L80", name: "Vitiligo" },
  { chapter: "L", code: "L89", name: "Úlcera de decúbito (escaras)" },
  { chapter: "L", code: "L97", name: "Úlcera do membro inferior não classificada em outra parte" },
  { chapter: "L", code: "L98", name: "Outras afecções da pele e do tecido subcutâneo" },

  // ── M: MUSCULOESQUELÉTICO ────────────────────────────────────────────────────
  { chapter: "M", code: "M00", name: "Artrite piogênica" },
  { chapter: "M", code: "M01", name: "Infecções diretas das articulações em doenças infecciosas e parasitárias" },
  { chapter: "M", code: "M05", name: "Artrite reumatoide soropositiva" },
  { chapter: "M", code: "M06", name: "Outras artrites reumatoides" },
  { chapter: "M", code: "M07", name: "Artropatias psoriásica e enteropatias" },
  { chapter: "M", code: "M08", name: "Artrite juvenil" },
  { chapter: "M", code: "M10", name: "Gota" },
  { chapter: "M", code: "M13", name: "Outras artrites" },
  { chapter: "M", code: "M15", name: "Poliartrose" },
  { chapter: "M", code: "M16", name: "Coxartrose – artrose do quadril" },
  { chapter: "M", code: "M17", name: "Gonartrose – artrose do joelho" },
  { chapter: "M", code: "M18", name: "Artrose da primeira articulação carpometacarpal" },
  { chapter: "M", code: "M19", name: "Outras artroses" },
  { chapter: "M", code: "M25", name: "Outros transtornos articulares (derrame articular, dor articular)" },
  { chapter: "M", code: "M30", name: "Poliarterite nodosa e afecções correlatas" },
  { chapter: "M", code: "M32", name: "Lúpus eritematoso sistêmico (LES)" },
  { chapter: "M", code: "M33", name: "Dermatomiosite e polimiosite" },
  { chapter: "M", code: "M34", name: "Esclerodermia sistêmica" },
  { chapter: "M", code: "M35", name: "Outras afecções sistêmicas do tecido conjuntivo (síndrome de Sjögren)" },
  { chapter: "M", code: "M40", name: "Cifose e lordose" },
  { chapter: "M", code: "M41", name: "Escoliose" },
  { chapter: "M", code: "M42", name: "Osteocondrose da coluna vertebral" },
  { chapter: "M", code: "M45", name: "Espondilite anquilosante" },
  { chapter: "M", code: "M47", name: "Espondilose" },
  { chapter: "M", code: "M48", name: "Outras espondilopatias (estenose do canal vertebral)" },
  { chapter: "M", code: "M50", name: "Transtornos dos discos cervicais" },
  { chapter: "M", code: "M51", name: "Outros transtornos dos discos intervertebrais (hérnia de disco lombar)" },
  { chapter: "M", code: "M54", name: "Dorsalgia (dor lombar, lombalgia, ciatalgia)" },
  { chapter: "M", code: "M60", name: "Miosite" },
  { chapter: "M", code: "M65", name: "Sinovite e tenossinovite" },
  { chapter: "M", code: "M70", name: "Transtornos dos tecidos moles relacionados com o uso, uso excessivo e pressão (bursite)" },
  { chapter: "M", code: "M75", name: "Lesões do ombro (síndrome do manguito rotador)" },
  { chapter: "M", code: "M76", name: "Entesopatias do membro inferior (tendinite patelar, fascite plantar)" },
  { chapter: "M", code: "M77", name: "Outras entesopatias (epicondilite – cotovelo do tenista)" },
  { chapter: "M", code: "M79", name: "Outros transtornos dos tecidos moles (fibromialgia)" },
  { chapter: "M", code: "M80", name: "Osteoporose com fratura patológica" },
  { chapter: "M", code: "M81", name: "Osteoporose sem fratura patológica" },
  { chapter: "M", code: "M85", name: "Outros transtornos da densidade e da estrutura ósseas" },
  { chapter: "M", code: "M86", name: "Osteomielite" },
  { chapter: "M", code: "M87", name: "Osteonecrose" },
  { chapter: "M", code: "M89", name: "Outros transtornos dos ossos" },

  // ── N: GENITURINÁRIO ─────────────────────────────────────────────────────────
  { chapter: "N", code: "N00", name: "Síndrome nefrítica aguda" },
  { chapter: "N", code: "N01", name: "Síndrome nefrítica rapidamente progressiva" },
  { chapter: "N", code: "N02", name: "Hematúria recidivante e persistente" },
  { chapter: "N", code: "N03", name: "Síndrome nefrítica crônica" },
  { chapter: "N", code: "N04", name: "Síndrome nefrótica" },
  { chapter: "N", code: "N05", name: "Síndrome nefrítica não especificada" },
  { chapter: "N", code: "N10", name: "Nefrite tubulo-intersticial aguda (pielonefrite aguda)" },
  { chapter: "N", code: "N11", name: "Nefrite tubulo-intersticial crônica (pielonefrite crônica)" },
  { chapter: "N", code: "N12", name: "Nefrite tubulo-intersticial não especificada" },
  { chapter: "N", code: "N13", name: "Uropatia obstrutiva e por refluxo" },
  { chapter: "N", code: "N17", name: "Insuficiência renal aguda (lesão renal aguda)" },
  { chapter: "N", code: "N18", name: "Insuficiência renal crônica (doença renal crônica)" },
  { chapter: "N", code: "N19", name: "Insuficiência renal não especificada" },
  { chapter: "N", code: "N20", name: "Calculose do rim e do ureter (litíase renal)" },
  { chapter: "N", code: "N21", name: "Calculose do aparelho urinário inferior" },
  { chapter: "N", code: "N23", name: "Cólica nefrética não especificada" },
  { chapter: "N", code: "N25", name: "Transtornos resultantes de função tubular renal alterada" },
  { chapter: "N", code: "N28", name: "Outros transtornos do rim e do ureter" },
  { chapter: "N", code: "N30", name: "Cistite" },
  { chapter: "N", code: "N34", name: "Uretrite e síndrome uretral" },
  { chapter: "N", code: "N35", name: "Estenose uretral" },
  { chapter: "N", code: "N39", name: "Outros transtornos do aparelho urinário (IU, infecção urinária)" },
  { chapter: "N", code: "N40", name: "Hiperplasia da próstata (HPB)" },
  { chapter: "N", code: "N41", name: "Doenças inflamatórias da próstata (prostatite)" },
  { chapter: "N", code: "N43", name: "Hidrocele e espermatocele" },
  { chapter: "N", code: "N44", name: "Torção do testículo" },
  { chapter: "N", code: "N45", name: "Orquite e epididimite" },
  { chapter: "N", code: "N48", name: "Outros transtornos do pênis (disfunção erétil)" },
  { chapter: "N", code: "N60", name: "Doença fibrocística da mama" },
  { chapter: "N", code: "N70", name: "Salpingite e ooforite" },
  { chapter: "N", code: "N71", name: "Doença inflamatória do útero, exceto o colo" },
  { chapter: "N", code: "N72", name: "Doença inflamatória do colo do útero (cervicite)" },
  { chapter: "N", code: "N73", name: "Outras doenças inflamatórias pélvicas femininas (doença inflamatória pélvica – DIP)" },
  { chapter: "N", code: "N76", name: "Outras afecções inflamatórias da vagina e da vulva (vaginite)" },
  { chapter: "N", code: "N80", name: "Endometriose" },
  { chapter: "N", code: "N81", name: "Prolapso genital feminino" },
  { chapter: "N", code: "N83", name: "Transtornos não inflamatórios do ovário, da tuba uterina e do ligamento largo" },
  { chapter: "N", code: "N85", name: "Outros transtornos não inflamatórios do útero (hiperplasia endometrial)" },
  { chapter: "N", code: "N87", name: "Displasia do colo do útero" },
  { chapter: "N", code: "N91", name: "Menstruação ausente, escassa e infrequente (amenorreia)" },
  { chapter: "N", code: "N92", name: "Menstruação excessiva, frequente e irregular (menorragia)" },
  { chapter: "N", code: "N93", name: "Outros sangramentos uterinos ou vaginais anormais (metrorragia)" },
  { chapter: "N", code: "N94", name: "Dor e outras afecções associadas com os órgãos genitais femininos (dismenorreia)" },
  { chapter: "N", code: "N95", name: "Transtornos da menopausa e da perimenopausa" },

  // ── O: GRAVIDEZ E PARTO ───────────────────────────────────────────────────────
  { chapter: "O", code: "O00", name: "Gravidez ectópica (tubária)" },
  { chapter: "O", code: "O02", name: "Outros produtos anormais da concepção (gravidez anembrionária)" },
  { chapter: "O", code: "O03", name: "Aborto espontâneo" },
  { chapter: "O", code: "O07", name: "Falha de tentativa de aborto" },
  { chapter: "O", code: "O08", name: "Complicações consecutivas ao aborto" },
  { chapter: "O", code: "O09", name: "Duração da gravidez" },
  { chapter: "O", code: "O10", name: "Hipertensão pré-existente que complica a gravidez" },
  { chapter: "O", code: "O11", name: "Transtornos hipertensivos pré-existentes com proteinúria superajuntada" },
  { chapter: "O", code: "O12", name: "Edema e proteinúria gestacionais" },
  { chapter: "O", code: "O13", name: "Hipertensão gestacional" },
  { chapter: "O", code: "O14", name: "Pré-eclâmpsia" },
  { chapter: "O", code: "O15", name: "Eclâmpsia" },
  { chapter: "O", code: "O20", name: "Hemorragia do início da gravidez (sangramento do 1º trimestre)" },
  { chapter: "O", code: "O21", name: "Vômitos excessivos na gravidez (hiperêmese gravídica)" },
  { chapter: "O", code: "O23", name: "Infecções do aparelho geniturinário na gravidez" },
  { chapter: "O", code: "O24", name: "Diabetes mellitus na gravidez" },
  { chapter: "O", code: "O25", name: "Desnutrição na gravidez" },
  { chapter: "O", code: "O26", name: "Cuidados prestados à mãe por outras afecções" },
  { chapter: "O", code: "O28", name: "Achados anormais na investigação pré-natal da mãe" },
  { chapter: "O", code: "O30", name: "Gestação múltipla (gêmeos)" },
  { chapter: "O", code: "O36", name: "Assistência prestada à mãe por outros problemas fetais conhecidos ou suspeitos" },
  { chapter: "O", code: "O41", name: "Outros transtornos do líquido amniótico e das membranas" },
  { chapter: "O", code: "O42", name: "Ruptura prematura de membranas" },
  { chapter: "O", code: "O44", name: "Placenta prévia" },
  { chapter: "O", code: "O45", name: "Descolamento prematuro da placenta" },
  { chapter: "O", code: "O60", name: "Trabalho de parto pré-termo" },
  { chapter: "O", code: "O62", name: "Anormalidades das forças de trabalho de parto" },
  { chapter: "O", code: "O69", name: "Trabalho de parto e parto complicados por afecções do cordão umbilical" },
  { chapter: "O", code: "O80", name: "Parto único espontâneo (parto normal)" },
  { chapter: "O", code: "O82", name: "Parto único por cesariana" },
  { chapter: "O", code: "O85", name: "Septicemia puerperal" },
  { chapter: "O", code: "O86", name: "Outras infecções puerperais" },
  { chapter: "O", code: "O90", name: "Complicações do período puerperal não classificadas em outra parte" },
  { chapter: "O", code: "O99", name: "Outras doenças da mãe classificadas em outra parte" },

  // ── R: SINTOMAS E SINAIS ─────────────────────────────────────────────────────
  { chapter: "R", code: "R00", name: "Anormalidades do batimento cardíaco (taquicardia, bradicardia)" },
  { chapter: "R", code: "R03", name: "Valores anormais de pressão arterial sem diagnóstico" },
  { chapter: "R", code: "R04", name: "Hemorragias das vias respiratórias (hemoptise, epistaxe)" },
  { chapter: "R", code: "R05", name: "Tosse" },
  { chapter: "R", code: "R06", name: "Anormalidades da respiração (dispneia, taquipneia)" },
  { chapter: "R", code: "R07", name: "Dor de garganta e no peito" },
  { chapter: "R", code: "R09", name: "Outros sintomas relativos ao aparelho circulatório e respiratório" },
  { chapter: "R", code: "R10", name: "Dor abdominal e pélvica" },
  { chapter: "R", code: "R11", name: "Náusea e vômitos" },
  { chapter: "R", code: "R12", name: "Azia" },
  { chapter: "R", code: "R13", name: "Disfagia" },
  { chapter: "R", code: "R14", name: "Flatulência e afecções correlatas" },
  { chapter: "R", code: "R15", name: "Incontinência fecal" },
  { chapter: "R", code: "R17", name: "Icterícia não classificada" },
  { chapter: "R", code: "R18", name: "Ascite" },
  { chapter: "R", code: "R19", name: "Outros sintomas relativos ao aparelho digestivo (hepatomegalia, massa abdominal)" },
  { chapter: "R", code: "R20", name: "Distúrbios da sensibilidade cutânea (parestesia, anestesia)" },
  { chapter: "R", code: "R21", name: "Erupção cutânea e outras lesões cutâneas inespecíficas" },
  { chapter: "R", code: "R22", name: "Tumefação, massa e caroço localizados da pele e do tecido subcutâneo" },
  { chapter: "R", code: "R25", name: "Movimentos involuntários anormais (tremor, espasmo)" },
  { chapter: "R", code: "R26", name: "Anormalidades da marcha e da mobilidade" },
  { chapter: "R", code: "R27", name: "Outros transtornos da coordenação (ataxia)" },
  { chapter: "R", code: "R30", name: "Dor associada à micção (disúria)" },
  { chapter: "R", code: "R31", name: "Hematúria não especificada" },
  { chapter: "R", code: "R32", name: "Incontinência urinária não especificada" },
  { chapter: "R", code: "R33", name: "Retenção urinária" },
  { chapter: "R", code: "R35", name: "Poliúria" },
  { chapter: "R", code: "R39", name: "Outros sintomas e sinais do aparelho urinário" },
  { chapter: "R", code: "R40", name: "Sonolência, estupor e coma" },
  { chapter: "R", code: "R41", name: "Outros sintomas relativos às funções cognitivas e à consciência (confusão, amnesia)" },
  { chapter: "R", code: "R42", name: "Tontura e instabilidade (vertigem)" },
  { chapter: "R", code: "R43", name: "Perturbações do olfato e do paladar" },
  { chapter: "R", code: "R44", name: "Outros sintomas e sinais relativos às sensações e percepções gerais (alucinações)" },
  { chapter: "R", code: "R45", name: "Sintomas e sinais relativos ao estado emocional (agitação, ansiedade)" },
  { chapter: "R", code: "R47", name: "Transtornos da fala não classificados em outra parte (disfasia, afasia)" },
  { chapter: "R", code: "R50", name: "Febre de causa desconhecida" },
  { chapter: "R", code: "R51", name: "Cefaleia" },
  { chapter: "R", code: "R52", name: "Dor não classificada em outra parte (dor crônica)" },
  { chapter: "R", code: "R53", name: "Mal-estar e fadiga (astenia)" },
  { chapter: "R", code: "R54", name: "Senilidade" },
  { chapter: "R", code: "R55", name: "Síncope e colapso (desmaio)" },
  { chapter: "R", code: "R56", name: "Convulsões não classificadas em outra parte" },
  { chapter: "R", code: "R57", name: "Choque não classificado em outra parte" },
  { chapter: "R", code: "R58", name: "Hemorragia não classificada em outra parte" },
  { chapter: "R", code: "R59", name: "Adenomegalia (linfadenomegalia)" },
  { chapter: "R", code: "R60", name: "Edema não classificado" },
  { chapter: "R", code: "R61", name: "Hiperhidrose (sudorese excessiva)" },
  { chapter: "R", code: "R62", name: "Retardo do desenvolvimento fisiológico normal" },
  { chapter: "R", code: "R63", name: "Sintomas relativos à alimentação e à ingestão de líquidos (anorexia, polifagia)" },
  { chapter: "R", code: "R65", name: "Síndrome de resposta inflamatória sistêmica (SIRS)" },
  { chapter: "R", code: "R68", name: "Outros sintomas e sinais gerais (calafrio, hipotermia)" },
  { chapter: "R", code: "R73", name: "Glicemia elevada (intolerância à glicose, hiperglicemia)" },
  { chapter: "R", code: "R74", name: "Valores anormais de enzimas séricas (elevação de TGO/TGP)" },
  { chapter: "R", code: "R76", name: "Outros achados imunológicos anormais no soro" },
  { chapter: "R", code: "R78", name: "Achado de drogas e outras substâncias no sangue" },
  { chapter: "R", code: "R79", name: "Outros achados laboratoriais anormais (eletrólitos, coagulação)" },

  // ── S-T: LESÕES E TRAUMATISMOS ───────────────────────────────────────────────
  { chapter: "S-T", code: "S00", name: "Traumatismo superficial da cabeça" },
  { chapter: "S-T", code: "S01", name: "Ferimento da cabeça" },
  { chapter: "S-T", code: "S02", name: "Fratura do crânio e dos ossos da face" },
  { chapter: "S-T", code: "S06", name: "Traumatismo intracraniano (concussão, contusão cerebral)" },
  { chapter: "S-T", code: "S09", name: "Outros traumatismos da cabeça e não especificados" },
  { chapter: "S-T", code: "S12", name: "Fratura do pescoço" },
  { chapter: "S-T", code: "S13", name: "Luxação, entorse e distensão das articulações e dos ligamentos do pescoço" },
  { chapter: "S-T", code: "S20", name: "Traumatismo superficial do tórax" },
  { chapter: "S-T", code: "S22", name: "Fratura de costela, do esterno e da coluna torácica" },
  { chapter: "S-T", code: "S27", name: "Traumatismo de outros órgãos intratorácicos" },
  { chapter: "S-T", code: "S30", name: "Traumatismo superficial do abdome, do dorso e da pelve" },
  { chapter: "S-T", code: "S32", name: "Fratura da coluna lombar e da pelve" },
  { chapter: "S-T", code: "S36", name: "Traumatismo de órgãos intra-abdominais" },
  { chapter: "S-T", code: "S40", name: "Traumatismo superficial do ombro e do braço" },
  { chapter: "S-T", code: "S42", name: "Fratura do ombro e do braço" },
  { chapter: "S-T", code: "S43", name: "Luxação, entorse e distensão das articulações do ombro" },
  { chapter: "S-T", code: "S50", name: "Traumatismo superficial do antebraço e do cotovelo" },
  { chapter: "S-T", code: "S52", name: "Fratura do antebraço" },
  { chapter: "S-T", code: "S60", name: "Traumatismo superficial do punho e da mão" },
  { chapter: "S-T", code: "S62", name: "Fratura ao nível do punho e da mão" },
  { chapter: "S-T", code: "S63", name: "Luxação, entorse e distensão das articulações do punho e da mão" },
  { chapter: "S-T", code: "S70", name: "Traumatismo superficial do quadril e da coxa" },
  { chapter: "S-T", code: "S72", name: "Fratura do fêmur (colo do fêmur)" },
  { chapter: "S-T", code: "S73", name: "Luxação do quadril" },
  { chapter: "S-T", code: "S80", name: "Traumatismo superficial da perna e do joelho" },
  { chapter: "S-T", code: "S82", name: "Fratura da perna, incluindo tornozelo" },
  { chapter: "S-T", code: "S83", name: "Luxação e entorse do joelho (lesão de ligamento cruzado, menisco)" },
  { chapter: "S-T", code: "S90", name: "Traumatismo superficial do tornozelo e do pé" },
  { chapter: "S-T", code: "S92", name: "Fratura do pé exceto tornozelo" },
  { chapter: "S-T", code: "S93", name: "Luxação e entorse do tornozelo e articulações do pé" },
  { chapter: "S-T", code: "T07", name: "Traumatismos múltiplos não especificados" },
  { chapter: "S-T", code: "T14", name: "Traumatismo de região não especificada do corpo" },
  { chapter: "S-T", code: "T36", name: "Intoxicação por antibióticos sistêmicos" },
  { chapter: "S-T", code: "T39", name: "Intoxicação por analgésicos, antipiréticos e anti-reumáticos não opioides" },
  { chapter: "S-T", code: "T40", name: "Intoxicação por narcóticos e psicodislépticos" },
  { chapter: "S-T", code: "T42", name: "Intoxicação por antiepilépticos, sedativos e hipnóticos" },
  { chapter: "S-T", code: "T43", name: "Intoxicação por substâncias psicotrópicas não classificadas em outra parte" },
  { chapter: "S-T", code: "T45", name: "Intoxicação por agentes que atuam principalmente sobre o sangue e órgãos hematopoéticos" },
  { chapter: "S-T", code: "T51", name: "Efeitos tóxicos do álcool" },
  { chapter: "S-T", code: "T54", name: "Efeitos tóxicos de substâncias corrosivas" },
  { chapter: "S-T", code: "T58", name: "Efeito tóxico do monóxido de carbono" },
  { chapter: "S-T", code: "T65", name: "Efeitos tóxicos de outras substâncias e das não especificadas" },
  { chapter: "S-T", code: "T78", name: "Efeitos adversos não classificados em outra parte (anafilaxia, alergia)" },
  { chapter: "S-T", code: "T79", name: "Algumas complicações precoces de traumatismo (embolia gordurosa)" },
  { chapter: "S-T", code: "T80", name: "Complicações consecutivas à perfusão, transfusão e injeção terapêutica" },
  { chapter: "S-T", code: "T81", name: "Complicações de procedimentos não classificadas em outra parte" },
  { chapter: "S-T", code: "T82", name: "Complicações de dispositivos protéticos cardíacos e vasculares" },

  // ── Z: FATORES QUE INFLUENCIAM ───────────────────────────────────────────────
  { chapter: "Z", code: "Z00", name: "Exame geral e investigação de pessoas sem queixas e sem diagnóstico estabelecido" },
  { chapter: "Z", code: "Z01", name: "Outros exames e investigações especiais de pessoas sem queixas" },
  { chapter: "Z", code: "Z03", name: "Observação e avaliação médica por suspeita de doenças e afecções" },
  { chapter: "Z", code: "Z04", name: "Exame e observação por outras razões" },
  { chapter: "Z", code: "Z08", name: "Exame de seguimento após tratamento por neoplasia maligna" },
  { chapter: "Z", code: "Z09", name: "Exame de seguimento após tratamento de outras afecções" },
  { chapter: "Z", code: "Z11", name: "Exame especial de rastreamento de doenças infecciosas e parasitárias" },
  { chapter: "Z", code: "Z12", name: "Exame especial de rastreamento de neoplasias" },
  { chapter: "Z", code: "Z13", name: "Exame especial de rastreamento de outras doenças" },
  { chapter: "Z", code: "Z23", name: "Necessidade de imunização isolada contra doenças bacterianas" },
  { chapter: "Z", code: "Z24", name: "Necessidade de imunização contra certas doenças virais" },
  { chapter: "Z", code: "Z25", name: "Necessidade de imunização contra outras doenças virais" },
  { chapter: "Z", code: "Z29", name: "Necessidade de outras medidas profiláticas" },
  { chapter: "Z", code: "Z30", name: "Anticoncepção" },
  { chapter: "Z", code: "Z34", name: "Supervisão de gravidez normal" },
  { chapter: "Z", code: "Z35", name: "Supervisão de gravidez de alto risco" },
  { chapter: "Z", code: "Z36", name: "Rastreamento pré-natal" },
  { chapter: "Z", code: "Z38", name: "Crianças nascidas vivas em função do local de nascimento" },
  { chapter: "Z", code: "Z39", name: "Cuidados e exames do pós-parto" },
  { chapter: "Z", code: "Z40", name: "Cirurgia profilática" },
  { chapter: "Z", code: "Z41", name: "Procedimentos para outras finalidades que não o tratamento" },
  { chapter: "Z", code: "Z45", name: "Ajuste e manuseio de dispositivos implantados" },
  { chapter: "Z", code: "Z46", name: "Ajuste e manuseio de outros dispositivos" },
  { chapter: "Z", code: "Z50", name: "Cuidados que envolvem o uso de procedimentos de reabilitação" },
  { chapter: "Z", code: "Z51", name: "Outros cuidados médicos (quimioterapia, radioterapia)" },
  { chapter: "Z", code: "Z54", name: "Convalescença" },
  { chapter: "Z", code: "Z57", name: "Exposição a fatores de risco ocupacional" },
  { chapter: "Z", code: "Z63", name: "Outros problemas relacionados com o grupo primário de apoio" },
  { chapter: "Z", code: "Z71", name: "Pessoas que entram em contato com serviços de saúde para outros procedimentos de aconselhamento" },
  { chapter: "Z", code: "Z75", name: "Problemas relacionados com as facilidades médicas e outros cuidados de saúde" },
  { chapter: "Z", code: "Z76", name: "Pessoas que entram em contato com serviços de saúde em outras circunstâncias" },
  { chapter: "Z", code: "Z80", name: "História familiar de neoplasia maligna" },
  { chapter: "Z", code: "Z82", name: "História familiar de certas incapacidades e doenças crônicas" },
  { chapter: "Z", code: "Z85", name: "História pessoal de neoplasia maligna" },
  { chapter: "Z", code: "Z87", name: "História pessoal de outras doenças e afecções" },
  { chapter: "Z", code: "Z88", name: "História pessoal de alergia a medicamentos e a substâncias biológicas" },
  { chapter: "Z", code: "Z91", name: "História pessoal de outros fatores de risco não classificados em outra parte" },
  { chapter: "Z", code: "Z95", name: "Presença de implantes e enxertos cardiovasculares" },
  { chapter: "Z", code: "Z96", name: "Presença de outros implantes funcionais" },
  { chapter: "Z", code: "Z98", name: "Outros estados pós-cirúrgicos" },
  { chapter: "Z", code: "Z99", name: "Dependência de máquinas e dispositivos, não classificada em outra parte" },
];

export function searchCID(query: string, chapter?: string): CIDEntry[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");

  return CID10_LIST.filter((e) => {
    if (chapter && chapter !== "all" && e.chapter !== chapter) return false;
    const code = e.code.toLowerCase();
    const name = e.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return code.includes(q) || name.includes(q);
  }).slice(0, 15);
}
