/**
 * medicamentosSUS.ts — Lista de medicamentos disponíveis no SUS (RENAME + apresentações)
 * Componente de Especialidade Farmacêutica Básica (CEAF) + Componente Básico
 */

export const MEDICAMENTOS_SUS: string[] = [
  // ─── PNEUMOLOGIA ───────────────────────────────────────────────────────────
  "Salbutamol spray 100mcg",
  "Salbutamol solução p/ nebulização 5mg/mL",
  "Salbutamol comprimido 4mg",
  "Formoterol + Budesonida 6/200mcg",
  "Formoterol + Budesonida 12/400mcg",
  "Formoterol fumarato 12mcg cápsula inalatória",
  "Beclometasona spray 250mcg",
  "Budesonida spray 200mcg",
  "Budesonida spray 400mcg",
  "Fluticasona spray 250mcg",
  "Brometo de Ipratrópio spray 0,02mg",
  "Brometo de Ipratrópio solução p/ nebulização 0,25mg/mL",
  "Tiotrópio 18mcg cápsula inalatória",
  "Aminofilina 100mg comprimido",
  "Teofilina 100mg comprimido",
  "Teofilina 200mg comprimido",
  "Montelucaste 5mg comprimido mastigável",
  "Montelucaste 10mg comprimido",
  "Prednisona 5mg comprimido",
  "Prednisona 20mg comprimido",
  "Prednisolona 3mg/mL solução oral",
  "N-acetilcisteína 600mg comprimido efervescente",
  "Ambroxol 30mg comprimido",

  // ─── CARDIOVASCULAR ────────────────────────────────────────────────────────
  "Losartana potássica 50mg",
  "Losartana potássica 100mg",
  "Valsartana 80mg",
  "Valsartana 160mg",
  "Enalapril 5mg",
  "Enalapril 10mg",
  "Enalapril 20mg",
  "Captopril 12,5mg",
  "Captopril 25mg",
  "Captopril 50mg",
  "Ramipril 5mg",
  "Ramipril 10mg",
  "Hidroclorotiazida 12,5mg",
  "Hidroclorotiazida 25mg",
  "Furosemida 40mg",
  "Furosemida 10mg/mL ampola",
  "Espironolactona 25mg",
  "Espironolactona 50mg",
  "Anlodipino 5mg",
  "Anlodipino 10mg",
  "Nifedipino 10mg (liberação imediata)",
  "Nifedipino 20mg (retard)",
  "Nifedipino 30mg (retard)",
  "Verapamil 80mg",
  "Verapamil 120mg",
  "Diltiazem 60mg",
  "Diltiazem 90mg",
  "Atenolol 25mg",
  "Atenolol 50mg",
  "Atenolol 100mg",
  "Metoprolol 25mg",
  "Metoprolol 50mg",
  "Metoprolol 100mg",
  "Propranolol 10mg",
  "Propranolol 40mg",
  "Carvedilol 3,125mg",
  "Carvedilol 6,25mg",
  "Carvedilol 12,5mg",
  "Carvedilol 25mg",
  "Bisoprolol 5mg",
  "Bisoprolol 10mg",
  "Sinvastatina 20mg",
  "Sinvastatina 40mg",
  "Sinvastatina 80mg",
  "Atorvastatina 10mg",
  "Atorvastatina 20mg",
  "Atorvastatina 40mg",
  "Atorvastatina 80mg",
  "Rosuvastatina 10mg",
  "Rosuvastatina 20mg",
  "Rosuvastatina 40mg",
  "AAS 100mg",
  "Clopidogrel 75mg",
  "Warfarina 5mg",
  "Digoxina 0,25mg",
  "Isossorbida mononitrato 20mg",
  "Isossorbida mononitrato 40mg",
  "Isossorbida dinitrato 5mg (sublingual)",
  "Amlodipino + Valsartana 5/80mg",
  "Amlodipino + Valsartana 5/160mg",
  "Hidralazina 25mg",
  "Hidralazina 50mg",
  "Clonidina 0,1mg",
  "Clonidina 0,2mg",
  "Doxazosina 2mg",
  "Doxazosina 4mg",
  "Ezetimiba 10mg",

  // ─── DIABETES ──────────────────────────────────────────────────────────────
  "Metformina 500mg",
  "Metformina 850mg",
  "Metformina 1000mg",
  "Metformina XR 500mg",
  "Metformina XR 750mg",
  "Glibenclamida 5mg",
  "Glipizida 5mg",
  "Glicazida 30mg MR",
  "Glicazida 60mg MR",
  "Glicazida 80mg",
  "Glimepirida 1mg",
  "Glimepirida 2mg",
  "Glimepirida 4mg",
  "Insulina NPH 100UI/mL",
  "Insulina Regular 100UI/mL",
  "Insulina Glargina 100UI/mL",
  "Insulina Detemir 100UI/mL",
  "Insulina Lispro 100UI/mL",
  "Insulina Aspart 100UI/mL",
  "Acarbose 50mg",
  "Acarbose 100mg",
  "Pioglitazona 15mg",
  "Pioglitazona 30mg",
  "Sitagliptina 100mg",
  "Vildagliptina 50mg",
  "Saxagliptina 5mg",
  "Empagliflozina 10mg",
  "Empagliflozina 25mg",
  "Dapagliflozina 10mg",
  "Canagliflozina 100mg",
  "Liraglutida 1,2mg/dose",
  "Liraglutida 1,8mg/dose",
  "Semaglutida 0,5mg/dose",
  "Semaglutida 1mg/dose",

  // ─── GASTROENTEROLOGIA ─────────────────────────────────────────────────────
  "Omeprazol 20mg",
  "Omeprazol 40mg",
  "Pantoprazol 20mg",
  "Pantoprazol 40mg",
  "Lansoprazol 15mg",
  "Lansoprazol 30mg",
  "Ranitidina 150mg",
  "Ranitidina 300mg",
  "Domperidona 10mg",
  "Metoclopramida 10mg",
  "Ondansetrona 4mg",
  "Ondansetrona 8mg",
  "Bromoprida 10mg",
  "Hioscina 10mg",
  "Loperamida 2mg",
  "Hidróxido de alumínio + magnésio suspensão",
  "Lactulose 667mg/mL solução oral",
  "Macrogol 3350 pó",

  // ─── NEUROLOGIA / PSIQUIATRIA ──────────────────────────────────────────────
  "Fluoxetina 20mg",
  "Sertralina 50mg",
  "Sertralina 100mg",
  "Escitalopram 10mg",
  "Escitalopram 20mg",
  "Paroxetina 20mg",
  "Paroxetina 40mg",
  "Amitriptilina 10mg",
  "Amitriptilina 25mg",
  "Amitriptilina 75mg",
  "Nortriptilina 25mg",
  "Nortriptilina 50mg",
  "Clonazepam 0,5mg",
  "Clonazepam 1mg",
  "Clonazepam 2mg",
  "Diazepam 2mg",
  "Diazepam 5mg",
  "Diazepam 10mg",
  "Haloperidol 1mg",
  "Haloperidol 5mg",
  "Risperidona 1mg",
  "Risperidona 2mg",
  "Risperidona 3mg",
  "Olanzapina 5mg",
  "Olanzapina 10mg",
  "Quetiapina 25mg",
  "Quetiapina 100mg",
  "Quetiapina 200mg",
  "Carbonato de lítio 300mg",
  "Carbamazepina 200mg",
  "Carbamazepina 400mg",
  "Fenitoína 100mg",
  "Ácido valpróico 250mg",
  "Valproato de sódio 500mg",
  "Levetiracetam 500mg",
  "Levetiracetam 1000mg",
  "Lamotrigina 25mg",
  "Lamotrigina 50mg",
  "Lamotrigina 100mg",
  "Topiramato 25mg",
  "Topiramato 50mg",
  "Gabapentina 300mg",
  "Gabapentina 400mg",
  "Pregabalina 75mg",
  "Pregabalina 150mg",
  "Donepezila 5mg",
  "Donepezila 10mg",
  "Memantina 10mg",
  "Levodopa + Carbidopa 250/25mg",

  // ─── ENDOCRINOLOGIA / TIREOIDE ─────────────────────────────────────────────
  "Levotiroxina 25mcg",
  "Levotiroxina 50mcg",
  "Levotiroxina 75mcg",
  "Levotiroxina 88mcg",
  "Levotiroxina 100mcg",
  "Levotiroxina 112mcg",
  "Levotiroxina 125mcg",
  "Levotiroxina 150mcg",
  "Levotiroxina 175mcg",
  "Levotiroxina 200mcg",
  "Metimazol 5mg",
  "Metimazol 10mg",
  "Propiltiouracila 100mg",
  "Cálcio carbonato 500mg",
  "Cálcio carbonato + vitamina D3 500mg/200UI",
  "Vitamina D3 1000UI",
  "Vitamina D3 2000UI",
  "Colecalciferol 7000UI (semanal)",
  "Ácido fólico 5mg",
  "Sulfato ferroso 40mg (Fe elementar)",
  "Sulfato ferroso 20mg/mL gotas",

  // ─── REUMATOLOGIA ──────────────────────────────────────────────────────────
  "Metotrexato 2,5mg",
  "Metotrexato 7,5mg",
  "Metotrexato 15mg",
  "Metotrexato 25mg",
  "Hidroxicloroquina 400mg",
  "Sulfassalazina 500mg",
  "Leflunomida 10mg",
  "Leflunomida 20mg",
  "Colchicina 0,5mg",
  "Alopurinol 100mg",
  "Alopurinol 300mg",
  "Febuxostate 80mg",
  "Cloroquina 150mg",

  // ─── INFECTOLOGIA / ANTIBIÓTICOS ───────────────────────────────────────────
  "Amoxicilina 500mg",
  "Amoxicilina + Ácido clavulânico 500/125mg",
  "Amoxicilina + Ácido clavulânico 875/125mg",
  "Azitromicina 500mg",
  "Claritromicina 250mg",
  "Claritromicina 500mg",
  "Doxiciclina 100mg",
  "Ciprofloxacino 500mg",
  "Levofloxacino 500mg",
  "Sulfametoxazol + Trimetoprim 400/80mg",
  "Metronidazol 250mg",
  "Metronidazol 400mg",
  "Nistatina suspensão 100.000UI/mL",
  "Fluconazol 150mg",
  "Fluconazol 50mg",

  // ─── CESSAÇÃO TABÁGICA ──────────────────────────────────────────────────────
  "Bupropiona 150mg (liberação sustentada)",
  "Vareniclina 0,5mg",
  "Vareniclina 1mg",
  "Nicotina 2mg (goma de mascar)",
  "Nicotina 4mg (goma de mascar)",
  "Nicotina 14mg/24h (adesivo transdérmico)",
  "Nicotina 21mg/24h (adesivo transdérmico)",
  "Nortriptilina 75mg (tabagismo)",

  // ─── OUTROS ────────────────────────────────────────────────────────────────
  "Alopurinol 100mg",
  "Finasterida 5mg",
  "Tansulosina 0,4mg",
  "Sildenafila 50mg",
  "Colestiramina 4g sachê",
  "Bezafibrato 400mg",
  "Fenofibrato 145mg",
  "Ciprofibrato 100mg",
  "Zolpidem 10mg",
  "Mirtazapina 15mg",
  "Mirtazapina 30mg",
  "Trazodona 50mg",
  "Trazodona 100mg",
  "Alprazolam 0,25mg",
  "Alprazolam 0,5mg",
  "Lorazepam 1mg",
  "Lorazepam 2mg",
  "Biperideno 2mg",
  "Ferro quelado glicinato 28mg",
  "Eritropoetina alfa 4000UI seringa",
  "Darbepoetin alfa 150mcg",
  "Alendrônico ácido 70mg (semanal)",
  "Risedronato 35mg (semanal)",
  "Ibandronato 150mg (mensal)",
  "Calcitonina 200UI spray nasal",
  "Ranelato de estrôncio 2g sachê",
  "Teriparatida 20mcg",
  "Denosumabe 60mg seringa",
  "Benidipino 4mg",
];
